# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AssignVariableOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AssignVariableOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAssignVariableOptions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def AssignVariableOptionsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x46\x4C\x33", size_prefixed=size_prefixed)

    # AssignVariableOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def AssignVariableOptionsStart(builder):
    builder.StartObject(0)

def Start(builder):
    AssignVariableOptionsStart(builder)

def AssignVariableOptionsEnd(builder):
    return builder.EndObject()

def End(builder):
    return AssignVariableOptionsEnd(builder)


class AssignVariableOptionsT(object):

    # AssignVariableOptionsT
    def __init__(self):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        assignVariableOptions = AssignVariableOptions()
        assignVariableOptions.Init(buf, pos)
        return cls.InitFromObj(assignVariableOptions)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, assignVariableOptions):
        x = AssignVariableOptionsT()
        x._UnPack(assignVariableOptions)
        return x

    # AssignVariableOptionsT
    def _UnPack(self, assignVariableOptions):
        if assignVariableOptions is None:
            return

    # AssignVariableOptionsT
    def Pack(self, builder):
        AssignVariableOptionsStart(builder)
        assignVariableOptions = AssignVariableOptionsEnd(builder)
        return assignVariableOptions
