# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BitcastOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BitcastOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBitcastOptions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BitcastOptionsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x46\x4C\x33", size_prefixed=size_prefixed)

    # BitcastOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def BitcastOptionsStart(builder):
    builder.StartObject(0)

def Start(builder):
    BitcastOptionsStart(builder)

def BitcastOptionsEnd(builder):
    return builder.EndObject()

def End(builder):
    return BitcastOptionsEnd(builder)


class BitcastOptionsT(object):

    # BitcastOptionsT
    def __init__(self):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        bitcastOptions = BitcastOptions()
        bitcastOptions.Init(buf, pos)
        return cls.InitFromObj(bitcastOptions)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, bitcastOptions):
        x = BitcastOptionsT()
        x._UnPack(bitcastOptions)
        return x

    # BitcastOptionsT
    def _UnPack(self, bitcastOptions):
        if bitcastOptions is None:
            return

    # BitcastOptionsT
    def Pack(self, builder):
        BitcastOptionsStart(builder)
        bitcastOptions = BitcastOptionsEnd(builder)
        return bitcastOptions
