# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

class BuiltinOptions2(object):
    NONE = 0
    StablehloConcatenateOptions = 1
    StablehloBroadcastInDimOptions = 2
    StablehloSliceOptions = 3
    StablehloConvolutionOptions = 4
    StablehloCustomCallOptions = 5
    StablehloReduceOptions = 6
    StablehloScatterOptions = 7
    StablehloCompareOptions = 8
    StablehloDynamicSliceOptions = 9
    StablehloPadOptions = 10
    StablehloIotaOptions = 11
    StablehloDotGeneralOptions = 12
    StablehloReduceWindowOptions = 13
    StablehloSortOptions = 14
    StablehloWhileOptions = 15
    StablehloGatherOptions = 16
    StablehloTransposeOptions = 17
    DilateOptions = 18
    StablehloRngBitGeneratorOptions = 19
    ReduceWindowOptions = 20

def BuiltinOptions2Creator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == BuiltinOptions2().StablehloConcatenateOptions:
        import tflite.StablehloConcatenateOptions
        return tflite.StablehloConcatenateOptions.StablehloConcatenateOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions2().StablehloBroadcastInDimOptions:
        import tflite.StablehloBroadcastInDimOptions
        return tflite.StablehloBroadcastInDimOptions.StablehloBroadcastInDimOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions2().StablehloSliceOptions:
        import tflite.StablehloSliceOptions
        return tflite.StablehloSliceOptions.StablehloSliceOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions2().StablehloConvolutionOptions:
        import tflite.StablehloConvolutionOptions
        return tflite.StablehloConvolutionOptions.StablehloConvolutionOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions2().StablehloCustomCallOptions:
        import tflite.StablehloCustomCallOptions
        return tflite.StablehloCustomCallOptions.StablehloCustomCallOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions2().StablehloReduceOptions:
        import tflite.StablehloReduceOptions
        return tflite.StablehloReduceOptions.StablehloReduceOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions2().StablehloScatterOptions:
        import tflite.StablehloScatterOptions
        return tflite.StablehloScatterOptions.StablehloScatterOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions2().StablehloCompareOptions:
        import tflite.StablehloCompareOptions
        return tflite.StablehloCompareOptions.StablehloCompareOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions2().StablehloDynamicSliceOptions:
        import tflite.StablehloDynamicSliceOptions
        return tflite.StablehloDynamicSliceOptions.StablehloDynamicSliceOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions2().StablehloPadOptions:
        import tflite.StablehloPadOptions
        return tflite.StablehloPadOptions.StablehloPadOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions2().StablehloIotaOptions:
        import tflite.StablehloIotaOptions
        return tflite.StablehloIotaOptions.StablehloIotaOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions2().StablehloDotGeneralOptions:
        import tflite.StablehloDotGeneralOptions
        return tflite.StablehloDotGeneralOptions.StablehloDotGeneralOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions2().StablehloReduceWindowOptions:
        import tflite.StablehloReduceWindowOptions
        return tflite.StablehloReduceWindowOptions.StablehloReduceWindowOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions2().StablehloSortOptions:
        import tflite.StablehloSortOptions
        return tflite.StablehloSortOptions.StablehloSortOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions2().StablehloWhileOptions:
        import tflite.StablehloWhileOptions
        return tflite.StablehloWhileOptions.StablehloWhileOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions2().StablehloGatherOptions:
        import tflite.StablehloGatherOptions
        return tflite.StablehloGatherOptions.StablehloGatherOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions2().StablehloTransposeOptions:
        import tflite.StablehloTransposeOptions
        return tflite.StablehloTransposeOptions.StablehloTransposeOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions2().DilateOptions:
        import tflite.DilateOptions
        return tflite.DilateOptions.DilateOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions2().StablehloRngBitGeneratorOptions:
        import tflite.StablehloRngBitGeneratorOptions
        return tflite.StablehloRngBitGeneratorOptions.StablehloRngBitGeneratorOptionsT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == BuiltinOptions2().ReduceWindowOptions:
        import tflite.ReduceWindowOptions
        return tflite.ReduceWindowOptions.ReduceWindowOptionsT.InitFromBuf(table.Bytes, table.Pos)
    return None
