# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DilateOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DilateOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDilateOptions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def DilateOptionsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x46\x4C\x33", size_prefixed=size_prefixed)

    # DilateOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def DilateOptionsStart(builder):
    builder.StartObject(0)

def Start(builder):
    DilateOptionsStart(builder)

def DilateOptionsEnd(builder):
    return builder.EndObject()

def End(builder):
    return DilateOptionsEnd(builder)


class DilateOptionsT(object):

    # DilateOptionsT
    def __init__(self):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        dilateOptions = DilateOptions()
        dilateOptions.Init(buf, pos)
        return cls.InitFromObj(dilateOptions)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, dilateOptions):
        x = DilateOptionsT()
        x._UnPack(dilateOptions)
        return x

    # DilateOptionsT
    def _UnPack(self, dilateOptions):
        if dilateOptions is None:
            return

    # DilateOptionsT
    def Pack(self, builder):
        DilateOptionsStart(builder)
        dilateOptions = DilateOptionsEnd(builder)
        return dilateOptions
