# automatically generated by the FlatBuffers compiler, do not modify

# namespace: tflite

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RightShiftOptions(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RightShiftOptions()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRightShiftOptions(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def RightShiftOptionsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x54\x46\x4C\x33", size_prefixed=size_prefixed)

    # RightShiftOptions
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def RightShiftOptionsStart(builder):
    builder.StartObject(0)

def Start(builder):
    RightShiftOptionsStart(builder)

def RightShiftOptionsEnd(builder):
    return builder.EndObject()

def End(builder):
    return RightShiftOptionsEnd(builder)


class RightShiftOptionsT(object):

    # RightShiftOptionsT
    def __init__(self):
        pass

    @classmethod
    def InitFromBuf(cls, buf, pos):
        rightShiftOptions = RightShiftOptions()
        rightShiftOptions.Init(buf, pos)
        return cls.InitFromObj(rightShiftOptions)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, rightShiftOptions):
        x = RightShiftOptionsT()
        x._UnPack(rightShiftOptions)
        return x

    # RightShiftOptionsT
    def _UnPack(self, rightShiftOptions):
        if rightShiftOptions is None:
            return

    # RightShiftOptionsT
    def Pack(self, builder):
        RightShiftOptionsStart(builder)
        rightShiftOptions = RightShiftOptionsEnd(builder)
        return rightShiftOptions
